### ISSUE TITLE
Permission to use code in project

### ISSUE THREAD

**Issue by Betalord** [dgmp88/MyGdxClasses#1]
Hey there,
since there is no way to contact you on GibHub, I had to open a new issue... :)
I was pointed to your MyShapeRenderer.java for rendering lines. Now I'd like to ask you permission to use this line drawing routine in my projects. May I? ;-)

**Comment by dglencross** [comment]
Hi, yes go for it. No need to credit but if you improve or expand the code we'd be interested to see it.

**Comment by Betalord** [comment]
Great! I certainly will (though I doubt that I will expand it). Thank you!
